### ISSUE TITLE
Link January article to website 

### ISSUE THREAD

**Issue by tracymiranda** [jonahgraham/eclipse.org-january#1]
The article about January that was part of the Eclipse newsletter should be linked from the new January website. 

https://www.eclipse.org/community/eclipse_newsletter/2016/november/article1.php

One idea is that it is connected to a 'Read More...' button in the 'What is January' section

**Comment by tracymiranda** [comment]
@jdarroy

**Comment by Jdarroy** [comment]
done

**Comment by jonahgraham** [comment]
Done
