### ISSUE TITLE
Review - 17 Apr

### ISSUE THREAD

**Issue by jonahgraham** [jonahgraham/eclipse.org-january#7]
- [x] Change download to 2.0.1
- [x] separate link to other downloads
- [x] fix spaces in punctuation
- [x] swap try it out with why use it (ordering)
- [x] remove who's involved
- [x] add resource section with links to PMI (https://projects.eclipse.org/projects/science.january), apidocs and nov 2016 article and science working group https://science.eclipse.org/
- [x] remove index.php and any other now unused files
- [x] investigate back maintaining scroll position
- [x] remove link to january-users
- [x] run site through linting tool and fix issues that are not present in Eclipse ICE's version
- [x] update copyright header to be:
```
<!-------------------------------------------------------------------------------
 - Copyright (c) 2013, 2017 The Eclipse Scout Team, UT-Battelle, LLC., Kichwa Coders Ltd and others.
 - All rights reserved. This program and the accompanying materials
 - are made available under the terms of the Eclipse Public License v1.0
 - which accompanies this distribution, and is available at
 - http://www.eclipse.org/legal/epl-v10.html
 -
 - Contributors:
 -   Initial API and implementation and/or initial documentation: Kichwa Coders Ltd. adopted from Eclipse ICE webpage.
 ------------------------------------------------------------------------------->
```

**Comment by jonahgraham** [comment]
@jdarroy I think if you comment on this bug then I can give you permission to check the check boxes.

**Comment by Jdarroy** [comment]
**Done**
Change download to 2.0.1
separate link to other downloads
fix spaces in punctuation
swap try it out with why use it (ordering)
remove who's involved - done
add resource section with links to PMI ...
remove index.php and any other now unused files
remove link to january-users - done
update copyright header to be:

**still working:**
investigate back maintaining scroll position
run site through linting tool and fix issues that are not present in Eclipse ICE's version

**Comment by jonahgraham** [comment]
All done! great.
